// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC67sAFJoLncH5DbW2c-ST_Ho-3CHram5s',
    appId: '1:168558415785:web:34f85d93fb0083d52dfeb8',
    messagingSenderId: '168558415785',
    projectId: 'pushnotification-d8f6a',
    authDomain: 'pushnotification-d8f6a.firebaseapp.com',
    databaseURL: 'https://pushnotification-d8f6a-default-rtdb.firebaseio.com',
    storageBucket: 'pushnotification-d8f6a.appspot.com',
    measurementId: 'G-SP9H55Z8QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbhSDDrEF_nNJ6diEMIP0w7OlkCJ0yKoI',
    appId: '1:168558415785:android:4e0515ed79123e712dfeb8',
    messagingSenderId: '168558415785',
    projectId: 'pushnotification-d8f6a',
    databaseURL: 'https://pushnotification-d8f6a-default-rtdb.firebaseio.com',
    storageBucket: 'pushnotification-d8f6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiOgrwtyXXkYgteZYcXVVXDHtVh3zL5ww',
    appId: '1:168558415785:ios:0c338fc5f0a4ad5a2dfeb8',
    messagingSenderId: '168558415785',
    projectId: 'pushnotification-d8f6a',
    databaseURL: 'https://pushnotification-d8f6a-default-rtdb.firebaseio.com',
    storageBucket: 'pushnotification-d8f6a.appspot.com',
    iosClientId: '168558415785-9e2n61ed8t608fgj37prahsmr49ubh5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase1',
  );
}
